/**
 * app.js — 360 Property Tour Engine
 * Reads from config.js (TOUR_CONFIG) and drives Pannellum.
 * Do NOT edit this file when reusing for a new property — edit config.js only.
 */

(function () {
  "use strict";

  // ── State ────────────────────────────────────────────────────
  let viewer        = null;
  let currentSceneId = null;

  // ── DOM refs (populated in init) ────────────────────────────
  let $viewer, $sceneNav, $badge, $subtitle, $caption, $loadOverlay, $loadMsg;

  // ── Build Pannellum scene map from config ────────────────────
  function buildScenes() {
    const scenes = {};
    TOUR_CONFIG.scenes.forEach(function (s) {
      const hotspots = (s.hotspots || []).map(function (h) {
        return {
          pitch:    h.pitch,
          yaw:      h.yaw,
          type:     "custom",
          text:     h.text,
          cssClass: "tour-hotspot",
          clickHandlerFunc: function () {
            switchScene(h.targetSceneId);
          }
        };
      });

      scenes[s.id] = {
        title:      s.title,
        panorama:   s.panorama,
        yaw:        s.yaw   || 0,
        pitch:      s.pitch || 0,
        hfov:       s.hfov  || 100,
        autoRotate: TOUR_CONFIG.autoRotateSpeed || 0,
        hotSpots:   hotspots
      };
    });
    return scenes;
  }

  // ── Initialise Pannellum viewer ──────────────────────────────
  function initViewer() {
    showLoading("Loading panorama…");

    const pannellumScenes = buildScenes();
    const defaultId = TOUR_CONFIG.defaultSceneId || TOUR_CONFIG.scenes[0].id;

    viewer = pannellum.viewer("panorama-viewer", {
      default: {
        firstScene:      defaultId,
        sceneFadeDuration: 600,
        autoLoad:        true,
        showControls:    false,     // We build our own controls
        keyboardZoom:    true,
        mouseZoom:       true,
        draggable:       true,
        disableKeyboardCtrl: false,
        hotSpotDebug:    false
      },
      scenes: pannellumScenes
    });

    viewer.on("load", function () {
      currentSceneId = viewer.getScene();
      hideLoading();
      updateSceneButtons(currentSceneId);
    });

    viewer.on("error", function (err) {
      showLoading("⚠ Panorama failed to load. Check image path in config.js.", true);
      console.error("Pannellum error:", err);
    });

    viewer.on("scenechange", function (sceneId) {
      currentSceneId = sceneId;
      updateSceneButtons(sceneId);
    });
  }

  // ── Scene switching ──────────────────────────────────────────
  function switchScene(sceneId) {
    if (!viewer || sceneId === currentSceneId) return;
    showLoading("Moving to next room…");
    viewer.loadScene(sceneId);
  }

  // ── Scene nav buttons ────────────────────────────────────────
  function buildSceneNav() {
    if (TOUR_CONFIG.scenes.length < 2) {
      $sceneNav.style.display = "none";
      return;
    }

    $sceneNav.innerHTML = "";

    TOUR_CONFIG.scenes.forEach(function (s) {
      const btn = document.createElement("button");
      btn.className   = "scene-btn";
      btn.dataset.id  = s.id;
      btn.textContent = s.title;

      if (s.thumbnail) {
        btn.style.backgroundImage = "url('" + s.thumbnail + "')";
        btn.classList.add("has-thumb");
      }

      btn.addEventListener("click", function () {
        switchScene(s.id);
      });

      $sceneNav.appendChild(btn);
    });
  }

  function updateSceneButtons(activeId) {
    const btns = $sceneNav.querySelectorAll(".scene-btn");
    btns.forEach(function (btn) {
      btn.classList.toggle("active", btn.dataset.id === activeId);
    });
  }

  // ── Loading overlay ──────────────────────────────────────────
  function showLoading(msg, isError) {
    $loadOverlay.style.display = "flex";
    $loadMsg.textContent       = msg || "Loading…";
    $loadOverlay.classList.toggle("is-error", !!isError);
  }

  function hideLoading() {
    $loadOverlay.style.display = "none";
  }

  // ── Fullscreen ───────────────────────────────────────────────
  function toggleFullscreen() {
    const el = document.getElementById("viewer-card");
    if (!document.fullscreenElement) {
      el.requestFullscreen && el.requestFullscreen();
    } else {
      document.exitFullscreen && document.exitFullscreen();
    }
  }

  // ── Zoom controls ────────────────────────────────────────────
  function zoomIn()  { if (viewer) viewer.setHfov(viewer.getHfov() - 10, true); }
  function zoomOut() { if (viewer) viewer.setHfov(viewer.getHfov() + 10, true); }

  // ── Inject property branding from config ────────────────────
  function applyBranding() {
    $badge.textContent    = TOUR_CONFIG.propertyTitle    || "Virtual Tour";
    $subtitle.textContent = TOUR_CONFIG.propertySubtitle || "";
    document.title        = TOUR_CONFIG.propertyTitle    || "360 Tour";
  }

  // ── Wire up static buttons ───────────────────────────────────
  function bindControls() {
    document.getElementById("btn-fullscreen").addEventListener("click", toggleFullscreen);
    document.getElementById("btn-zoom-in").addEventListener("click", zoomIn);
    document.getElementById("btn-zoom-out").addEventListener("click", zoomOut);

    document.addEventListener("fullscreenchange", function () {
      const icon = document.querySelector("#btn-fullscreen .icon");
      if (icon) icon.textContent = document.fullscreenElement ? "⤡" : "⛶";
    });
  }

  // ── Entry point ──────────────────────────────────────────────
  function init() {
    $viewer      = document.getElementById("panorama-viewer");
    $sceneNav    = document.getElementById("scene-nav");
    $badge       = document.getElementById("property-title");
    $subtitle    = document.getElementById("property-subtitle");
    $loadOverlay = document.getElementById("load-overlay");
    $loadMsg     = document.getElementById("load-msg");

    applyBranding();
    buildSceneNav();
    bindControls();
    initViewer();
  }

  document.addEventListener("DOMContentLoaded", init);

})();
